version: '3.8'

services:
  webapi:
    image: webapi-mongo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - DatabaseSettings__ConnectionString=mongodb://gbs:geheim@mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gbs
      - MONGO_INITDB_ROOT_PASSWORD=geheim
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: